bug# 671 Calling EtomoDirector.getInstance() in AxisID prior to running AxisID() is causing a NoClassDefFoundError when running JUnit.  Change code to call EtomoDirector.getInstance the first time getExtension is run.